version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://postgres:@db:5432/demoapp
    build: .
    command: bundle exec rails s
    volumes:
      - .:/demoapp
    ports:
      - "3000:3000"
    depends_on:
      - db
